### PR TITLE
Tls upgrade

### PR DESCRIPTION
**Pull request by LukeFieldsend**
Mono httpClient does not support tls 1.1 and 1.2. switched the sdk over to use the native httpClient implementations for the ios and Android platforms. Fun side effect, the payment is now twice as fast

### CODE REVIEW

**Comment by LukeFieldsend** [comment]
@IgorCandido @hirenhirani @daningrey @mcintyre321 @James-Lappin @himanshuatjudo @akakjs

**Comment by simonjudoduff** [comment]
:+1:

**Comment by hirenhirani** [comment]
:+1:

**Comment by daningrey** [comment]
:+1:

**Pull request merged**
